### ISSUE TITLE
請問要如何添加其他軟件包 ?

### ISSUE THREAD

**Issue by pig1209** [VergilGao/openwrt-compiler#1]
比如說要增加 https://github.com/kenzok8/openwrt-packages
這裡的 luci-app-ssr-plus、luci-app-vssr
請問要修改那裡? 謝謝

**Comment by VergilGao** [comment]
action里 run workflow
填true
然后等出ssh连接地址之后，ssh上去自己编译
编译好后下载下来的文件里有config.info，复制替换文本.config文件里的内容

**Comment by pig1209** [comment]
謝謝您的回覆
現在只要ssh進去,之後编译都會報錯,
您說"编译好后下载下来的文件里有config.info"
是指make menuconfig之後 ,在ssh模式下就可以download嗎?
因為既然已编译好,檔案已產生, 
為何還要作下列這個動作?
 "下载下来的文件里有config.info，复制替换文本.config文件里的内容"

**Comment by VergilGao** [comment]
> 謝謝您的回覆
> 現在只要ssh進去,之後编译都會報錯,
> 您說"编译好后下载下来的文件里有config.info"
> 是指make menuconfig之後 ,在ssh模式下就可以download嗎?
> 因為既然已编译好,檔案已產生,
> 為何還要作下列這個動作?
> "下载下来的文件里有config.info，复制替换文本.config文件里的内容"

因为你要把你修改的配置上传才能在下次编译的时候不用重新修改配置。
